[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veiled_chests = "9igfhJeu5kP8jyXJ1Li5TGS8G5KyYNExLBH6YUP6d6Jv"

[programs.localnet]
veiled_chests = "9igfhJeu5kP8jyXJ1Li5TGS8G5KyYNExLBH6YUP6d6Jv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 30000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ"
program = "artifacts/arcium_program_0.6.3.so"

[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "8snfPfMYu3KaueWE79seRqFeYSxzZEgVZ914JfiRvCGP"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7Siux8am1QYYP6H1kx917GxuuBwV3CedW85wQz7kAdXn"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "DYLmLBwZAmm3k9bZBeYqUmMoTcqUBteSzQYEnbJFh5kb"
filename = "artifacts/wallet_acc_DYLm_h5kb.json"

[[test.validator.account]]
address = "pKRNeuRtQRnST3HKzZBGhT23WrFjX6rJ69rfwGvFQf6"
filename = "artifacts/arx_ata_DYLm_h5kb.json"

[[test.validator.account]]
address = "FpD1na9g8QTSEVp7MJ8yWS377NPHDNnxkXhjrVjLmvW2"
filename = "artifacts/wallet_acc_FpD1_mvW2.json"

[[test.validator.account]]
address = "D2YJeUYJQqFD3RmnK1zUTrfNMwzkXu9xr2CnrFhqDcrs"
filename = "artifacts/wallet_acc_callback_D2YJ_Dcrs.json"

[[test.validator.account]]
address = "A6hzQQ9YgXimhJG7APd74iMRk2nGzM9KfUsN6veXPJCx"
filename = "artifacts/arx_ata_FpD1_mvW2.json"

[[test.validator.account]]
address = "8EGVfqJ1wEL6cVkBDoj6CRopTAsdSH4KkhetERT5ABEq"
filename = "artifacts/operator_acc_FpD1_mvW2.json"

[[test.validator.account]]
address = "GXAmi5GPSexbEQMWuWoWXb7sxJVYGAJwFy7M5hwZdkqT"
filename = "artifacts/arx_node_FpD1_mvW2.json"

[[test.validator.account]]
address = "8NZ4xGEv8FTvKGrYoH2cke5KH1U63TKysh8SQpwigpok"
filename = "artifacts/wallet_acc_8NZ4_gpok.json"

[[test.validator.account]]
address = "6ozrFMNgeqEg15bQxGQsspbAgz6TT7bMecDZ59regQYh"
filename = "artifacts/wallet_acc_callback_6ozr_gQYh.json"

[[test.validator.account]]
address = "HcxiihgnYocN4P39nqZNi3EYx2tczEGbYaPzycCwjJWi"
filename = "artifacts/arx_ata_8NZ4_gpok.json"

[[test.validator.account]]
address = "69VMAwTm5j4W7vhyV1Q42NW9NEbp5686d7o9EyHYiKmz"
filename = "artifacts/operator_acc_8NZ4_gpok.json"

[[test.validator.account]]
address = "CUF5HgJk6eJr9YQCZovcq7N4jMrRt2wUmUGfUXhS9Xew"
filename = "artifacts/arx_node_8NZ4_gpok.json"

[[test.validator.account]]
address = "5QPigYqE4Deg2Ym5Hw7m8iTT4qudpcG5bfJ7wseN9QgP"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "3xAFRJDxLvu1nHSXNz8sCZ3W1B9RDrNw7nFPegf5gDeL"
filename = "artifacts/play_chest_game_raw_circuit_0.json"

[[test.validator.account]]
address = "DeJCV8vUuZXuHYJ5ex3nVXG6CBo914J9NVY3JtsNEkvc"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "MKJgf1Ted3dmbQGTqxcLFMPoMUBCi2AS2Gpv3bUnFDb"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "8MjAU11fHkUZQDkwx2XCrGR53j7RHJuf8SDa2u2DHEqK"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "7VYoXbzfgQuchozYbynA3dZXGuhF5hgFinCkHVJjJHHD"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "HivZUTBWmuzV59CpC42CwZW4nbvxKWhRhaLDTH7tPsG"
filename = "artifacts/executing_pool_acc.json"
[[test.genesis]] # arcium:autogenerated
address = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" # arcium:autogenerated
program = "/workspaces/Alloy/artifacts/arcium_program_0.6.3.so" # arcium:autogenerated
upgradeable = true  # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "6mEn18Q99FqUTqHg5vthrbZxvMnafQrxeLcr9EZC2CKw" # arcium:autogenerated
filename = "artifacts/wallet_acc_6mEn_2CKw.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7ihUhQRmJMKkxRjAJrmDNFPrMdCkz2CDfiiU44N3J7Y9" # arcium:autogenerated
filename = "artifacts/arx_ata_6mEn_2CKw.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7v7HUZtc96Hig8MxiYnX4tC6n4g8ZrjiKTZGrT7dsAH6" # arcium:autogenerated
filename = "artifacts/wallet_acc_7v7H_sAH6.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "9j7HBFvYwtDUWXMGVZ7qkUi5uBf9dXGeYsy63D4K7DvQ" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_9j7H_7DvQ.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7XPpMS7d9NzsKQGPo5WgKwdsdFftxg7iueoqeacKNcSP" # arcium:autogenerated
filename = "artifacts/arx_ata_7v7H_sAH6.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "VMod4TPjLaAamcsEudtvE9DUKvo58T9Br4v333U4gwL" # arcium:autogenerated
filename = "artifacts/operator_acc_7v7H_sAH6.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "A1N143n3x4iF7wfvqiqFXtbQxnyNaHBySnPcaYmi9Xak" # arcium:autogenerated
filename = "artifacts/arx_node_7v7H_sAH6.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7mjfNNU7r8sBZ417qgfFsRrqmsULjDhWA9n786suPdYy" # arcium:autogenerated
filename = "artifacts/wallet_acc_7mjf_PdYy.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "8GCZQoQzmRMQCTRPdardrFAcqmQukaV1PCMqPZzVh6iH" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_8GCZ_h6iH.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "BRiMMKJquCG4KbteJvZwhyAY2stqtQpnJtoL2ihqxCha" # arcium:autogenerated
filename = "artifacts/arx_ata_7mjf_PdYy.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "3CWjnYuKo7DJ1JukZUKjz5NGoFEEfU6YbAz24V3BidLC" # arcium:autogenerated
filename = "artifacts/operator_acc_7mjf_PdYy.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "6vNwQe3fiU1u4JxTM2XkvPou9uH7EZNrskLZJrRYM8WJ" # arcium:autogenerated
filename = "artifacts/arx_node_7mjf_PdYy.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "D75nYPZEh81sBHydJvW4x4LNdhRUEXtLUFqzSk5D1fwG" # arcium:autogenerated
filename = "artifacts/wallet_acc_recovery_peer_0.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "DZvt3rmVMYMwj9znCnTeiyAvfxaVnfCqq45id82773b6" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_recovery_peer_0.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "4r2qLwkeruPkZdpiynKdomcVUGFsEY2ur38dr33J7xTb" # arcium:autogenerated
filename = "artifacts/arx_ata_recovery_peer_0.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "8fHgReDNKxe3kzyL7vjCwiULZu11kDetJhfNnzKo8qHE" # arcium:autogenerated
filename = "artifacts/operator_acc_recovery_peer_0.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "6ujv8vAQMpTmmPiqZWYphrSuroFhfrtDNdvBPidP5pqb" # arcium:autogenerated
filename = "artifacts/arx_node_recovery_peer_0.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "CEyBZGJoRESZjb3VKXCJhFMrYW99wNU6EKpXVc58HyTT" # arcium:autogenerated
filename = "artifacts/wallet_acc_recovery_peer_1.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "GhjE5zZcDjuqbaUpgg6MrCBbHzR5DMm5rtCRiMBWH2Kp" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_recovery_peer_1.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "CuCWHUaJ8sfJPgQE6s5Ks6MsRCmhmEKVHQvvze3mWzSs" # arcium:autogenerated
filename = "artifacts/arx_ata_recovery_peer_1.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "FES75hW4W2LcCRV8YeKb9YcPmCRhJ3iWLrsTX4JiCM1K" # arcium:autogenerated
filename = "artifacts/operator_acc_recovery_peer_1.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7TMENQXqfug9pgcCmuZzn5dgpnYPDmnNUHHjBMPHdwjF" # arcium:autogenerated
filename = "artifacts/arx_node_recovery_peer_1.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "CHKwTgAeufBM2gZw45wNXZiXS6Lbn27tJNgFp43Ki5rx" # arcium:autogenerated
filename = "artifacts/wallet_acc_recovery_peer_2.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "4bDZi1GNTkk57cqBWXUNZY4Va1N83ppfMtB39uoMS8in" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_recovery_peer_2.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "6EEzrrzD8iTosguYDxxdTKPvUw8EYQtVZhH1QS6FJDuN" # arcium:autogenerated
filename = "artifacts/arx_ata_recovery_peer_2.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "E5EDcMBVihzspVbfnexuKKJ1zJK7RcgDgRyLGAKnSNA" # arcium:autogenerated
filename = "artifacts/operator_acc_recovery_peer_2.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "4uwLw4iJUB6vNfvH9iXizDwhQxMtJKNyYLJ6KeVbVvbs" # arcium:autogenerated
filename = "artifacts/arx_node_recovery_peer_2.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "2w5RRUkCahHPjopUPLduSpd6rKSUvhzyHNRZjmUDry8U" # arcium:autogenerated
filename = "artifacts/wallet_acc_recovery_peer_3.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "GVFd1xYjdKg3sQv5L45ebYwGAWEHJZrarSYcaDCdKBFs" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_recovery_peer_3.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "2rKTPyfPstk5JSvesTVxXtYrfccJ4rpHpP3aBG76pJpc" # arcium:autogenerated
filename = "artifacts/arx_ata_recovery_peer_3.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "5bPkbrRUFLQwhM2j73dHajZgSPBH5jSkXdPyKLBSND98" # arcium:autogenerated
filename = "artifacts/operator_acc_recovery_peer_3.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "FpHcqK9yuF7oVhkfdLQFHm5jSH9KuhLkcQsvGQbcxMJx" # arcium:autogenerated
filename = "artifacts/arx_node_recovery_peer_3.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "41SqVLdcxguhXFfVkRZJgjHaRhNdoVEjW6jbvTa1cSrC" # arcium:autogenerated
filename = "artifacts/wallet_acc_recovery_peer_4.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "7ap278ZfyVJWFnQd6xa5WH6W8Boa9dqFoqhh8imtWNbw" # arcium:autogenerated
filename = "artifacts/wallet_acc_callback_recovery_peer_4.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "Gt4tm2bbGvFz6nHqoJSJh7qJkxXWA2GbR5tdL9bfrfrC" # arcium:autogenerated
filename = "artifacts/arx_ata_recovery_peer_4.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "wGMhDY1Yp2AbvdYjB6bmHqsNCF8AHXw74Uqk1iD1iSD" # arcium:autogenerated
filename = "artifacts/operator_acc_recovery_peer_4.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "2SgdPeKeLwQ2MSJgwPU3pn2pbphqbbqZMqjHdTJDW9p1" # arcium:autogenerated
filename = "artifacts/arx_node_recovery_peer_4.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "J48otLKR2d4eGmtGqD7gpYuMePmGrPXJJ2HnaEhPKHB9" # arcium:autogenerated
filename = "artifacts/mxe_key_recovery_init_comp.json" # arcium:autogenerated

[[test.validator.account]] # arcium:autogenerated
address = "DhPnLFF2jRE11zY5K3Pd6Waokcmb7f72KSLdUyW4wQG2" # arcium:autogenerated
filename = "artifacts/recovery_cluster_acc.json" # arcium:autogenerated
