[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veiled_chests = "BK7k8VuAAZ5Cw9MQNuGT4D7d6ampq3BFGrkdPwAaVfES"

[programs.localnet]
veiled_chests = "BK7k8VuAAZ5Cw9MQNuGT4D7d6ampq3BFGrkdPwAaVfES"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ"
program = "artifacts/arcium_program_0.7.0.so"

[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
